---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - composer install --optimize-autoloader --no-dev
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan optimize
    - chmod -R 775 storage bootstrap/cache
